### ISSUE TITLE
SOP wording

### ISSUE THREAD

**Issue by josephlhall** [linuxwolf/ietf-saa#3]
This text:

>A report made by a member of the SAA team should include a suggested action in response, including specific text for email(s) to the original poster and/or the list, as appropriate.

Seems to read better as "A report made to a member of the SAA team..." or is this just jumping to the response from the SAA and that's also called a "report"?

**Comment by coopdanger** [comment]
Yeah this became unclear in the last round of edits. I attempted a fix: https://github.com/linuxwolf/ietf-saa/commit/d90b987f39d603e815c40564d5b20ce887af9e0a#diff-d0a3958905c0e9b3fadf324687a2255f

**Comment by josephlhall** [comment]
WFM! Thanks
